services:
  postgres:
    container_name: userManagementContainer
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: root
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  usermanagement:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userManagementApp
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      DB_DRIVER: postgres
      DB_SOURCE: "postgresql://root:secret@postgres:5432/root?sslmode=disable"
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: user_events
    entrypoint:
      - sh
      - -c
      - |
        set -xe
        until psql -h postgres -U root -c '\dt'; do echo "waiting for postgres..."; sleep 1; done
        ./UserManagement    

volumes:
  postgres-data:
